name: Rust

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: "Build and test ${{ matrix.os }}"
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
